# ruff.toml
target-version = "py312"
line-length = 140
exclude = ["venv"]

[lint]
select = ["E", "F", "I", "B", "UP", "SIM", "C4", "N", "PL"]
ignore = ["E501"]  # long lines are handled by black

[lint.isort]
known-first-party = ["api", "ui", "common", "framework", "config"]

[lint.flake8-pytest-style]
disable-attrs = ["D100", "D101", "D102", "D103", "D104", "D105", "D106"]

[format]
quote-style = "double"
indent-style = "space"
